### ISSUE TITLE
ValueError: Extra data

### ISSUE THREAD

**Issue by sabertooth0915** [CRutkowski/Kijiji-Scraper#33]
I have encountered this error many times. Had to remove ads.json to fix and it kept getting this error every several days.  (really like this project BTW)

**********@ubuntu-upstart:~# kijiji
No config file loaded
Ads file: /root/.kijiji_scraper/ads.json
Traceback (most recent call last):
  File "/usr/local/bin/kijiji", line 9, in <module>
    load_entry_point('kijiji-scraper==3.0.1', 'console_scripts', 'kijiji')()
  File "/usr/local/lib/python3.4/dist-packages/kijiji_scraper-3.0.1-py3.4.egg/kijiji_scraper/launcher.py", line 72, in main
    kijiji_scraper = KijijiScraper(ads_filepath)
  File "/usr/local/lib/python3.4/dist-packages/kijiji_scraper-3.0.1-py3.4.egg/kijiji_scraper/kijiji_scraper.py", line 18, in __init__
    self.load_ads()
  File "/usr/local/lib/python3.4/dist-packages/kijiji_scraper-3.0.1-py3.4.egg/kijiji_scraper/kijiji_scraper.py", line 32, in load_ads
    self.all_ads = json.load(ads_file)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3722674 - line 1 column 3723400 (char 3722673 - 3723399)

**Comment by tristanlatr** [comment]
Please try with a supported version of Python - let's says python3.8.

**Comment by sabertooth0915** [comment]
Got the chance to use Python 3.8 and still got this error 
Loaded config file: /home/KJ/config.yaml
Ads file: /root/.kijiji_scraper/ads.json
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    if __name__ == "__main__": main()
  File "/home/KJ/kijiji_scraper/launcher.py", line 72, in main
    kijiji_scraper = KijijiScraper(ads_filepath)
  File "/home/KJ/kijiji_scraper/kijiji_scraper.py", line 18, in __init__
    self.load_ads()
  File "/home/KJ/kijiji_scraper/kijiji_scraper.py", line 32, in load_ads
    self.all_ads = json.load(ads_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3411738 (char 3411737)
